# Generated by Django 3.1.13 on 2021-09-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugat',
            name='adabiy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Adabiy (soz)'),
        ),
        migrations.AlterField(
            model_name='lugat',
            name='xorazmcha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xorazm (soz)'),
        ),
    ]
